"ノーマル":
  r: 144
  g: 153
  b: 161
"ほのお":
  r: 255
  g: 156
  b: 84
"みず":
  r: 77
  g: 144
  b: 213
"でんき":
  r: 243
  g: 210
  b: 59
"くさ":
  r: 99
  g: 187
  b:  91
"こおり":
  r: 116
  g: 206
  b: 192
"かくとう":
  r: 206
  g: 64
  b: 105
"どく":
  r: 171
  g: 106
  b: 200
"じめん":
  r: 217
  g: 119
  b: 70
"ひこう":
  r: 143
  g: 168
  b: 221
"エスパー":
  r: 249
  g: 113
  b: 118  
"むし":
  r: 144
  g: 193
  b: 44
"いわ":
  r: 199
  g: 183
  b: 139
"ゴースト":
  r: 82
  g: 105
  b: 172
"ドラゴン":
  r: 10
  g: 109
  b: 196
"あく":
  r: 90
  g: 83
  b: 102
"はがね":
  r: 90
  g: 142
  b: 161
"フェアリー":
  r: 236
  g: 143
  b: 230