# サーバ
server:
  name: API
  port: ${PORT:8080}
  # フロント側のorigin（区切り文字:"|"）
  client.origin: pokego-data-cl.herokuapp.com|pokego.brainjuice.jp
  
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/pokemon
#    username: postgres
#    password: password
#    driverClassName: org.postgresql.Driver

#spring:
#  datasource:
#    url: jdbc:h2:./pokemonH2Db
#    driverClassName: org.h2.Driver
#    initialization-mode: never
#    schema: classpath:schema.sql
#    data: classpath:data.sql
#  h2.console.enabled: false
    
jwt.uuid: 00855fa1-4320-5cfb-0396-597a06af3ff2

# ロギング
logging:
  config: classpath:logback/logback-production.xml
  level:
    root: INFO
    org:
      springframework.web.client.RestTemplate: INFO
#      hibernate:
#        SQL: INFO
#        type.descriptor.sql.BasicBinder: INFO

# Redis
redis:
  env:
    url: REDIS_URL

# AWS
aws:
  s3:
    accessKey: S3_ACCESS_KEY_ID
    secretAccessKey: S3_SECRET_ACCESS_KEY
    endpoint: https://s3-us-west-1.amazonaws.com/static.brainjuice.jp/
    s3BacketName: static.brainjuice.jp
    suffix: ""