# サーバ
server:
  name: API
  port: ${PORT:8080}
  # フロント側のorigin（区切り文字:"|"）
  client.origin: pokego-data-cl.herokuapp.com|pokego.brainjuice.jp

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
    driverClassName: org.postgresql.Driver
    hikari:
      data-source-properties:
        sslmode: require
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate:
      session_factory.statement_inspector: jp.brainjuice.pokego.dao.jpa.inspector.SqlInspector
      use_sql_comments: true
    open-in-view: false
  data.redis.url: ${REDIS_URL}
  servlet.multipart:
    max-file-size: 32MB
    max-request-size: 32MB
  messages:
    basename: application-messages

jwt.cryptoKey: ${CRYPTO_KEY:}

# ロギング
logging:
  config: classpath:logback/logback-staging.xml
  level:
    root: INFO
    org:
      springframework:
        web:
          client:
            RestTemplate: INFO
        data:
          redis:
            core: INFO
            connection: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
    jp:
      brainjuice:
        pokego:
          business:
            dao:
              inspector:
                SqlInspector: INFO
          config:
            RedisAspect: INFO

# AWS
aws:
  s3:
    accessKey: ${S3_ACCESS_KEY_ID}
    secretAccessKey: ${S3_SECRET_ACCESS_KEY}
    endpoint: https://s3-us-west-1.amazonaws.com/static.brainjuice.jp/
    s3BacketName: static.brainjuice.jp
    suffix: -staging