# サーバ
server:
  name: API
  port: ${PORT:8080}
  # フロント側のorigin（区切り文字:"|"）
  client.origin: localhost:3000|brainjuice-app-staging.herokuapp.com|brainjuice.jp

spring:
  datasource:
    url: ${DATABASE_URL:postgresql://localhost:5432/POKEMON}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate:
      session_factory.statement_inspector: jp.brainjuice.pokego.business.dao.inspector.SqlInspector
      use_sql_comments: true
    open-in-view: false

    
jwt.uuid: ${JWT_UUID:}

# ロギング
logging:
  config: classpath:logback/logback-develop.xml
  level:
    root: INFO
    org:
      "[springframework.web.client.RestTemplate]": INFO
      hibernate:
        SQL: DEBUG
        "[type.descriptor.sql.BasicBinder]": TRACE
    "[jp.brainjuice.pokego.business.dao.inspector.SqlInspector]": DEBUG

# Redis
redis:
  env:
    url: ${REDIS_URL}

# AWS
aws:
  s3:
    accessKey: ${S3_ACCESS_KEY_ID}
    secretAccessKey: ${S3_SECRET_ACCESS_KEY}
    endpoint: https://s3-us-west-1.amazonaws.com/static.brainjuice.jp/
    s3BacketName: static.brainjuice.jp
    suffix: -test