# サーバ
server:
  name: API
  port: ${PORT:8080}
  # フロント側のorigin（区切り文字:"|"）
  client.origin: localhost:3000|brainjuice-app-staging.herokuapp.com|brainjuice.jp
  
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/pokemon
#    username: postgres
#    password: password
#    driverClassName: org.postgresql.Driver

spring:
  datasource:
    url: jdbc:h2:./pokemonH2Db
    driverClassName: org.h2.Driver
    initialization-mode: never
    schema: classpath:schema.sql
    data: classpath:data.sql
  h2.console.enabled: false
    
jwt.uuid: 00855fa1-4320-5cfb-0396-597a06af3ff2

# ロギング
logging:
  config: classpath:logback/logback-develop.xml
  level:
    root: INFO
    org:
      springframework.web.client.RestTemplate: INFO

# AWS
aws:
  s3:
    accessKey: AKIA3GIM5NDHYCBEOTGQ
    secretAccessKey: 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
    endpoint: https://s3-us-west-1.amazonaws.com/static.brainjuice.jp/
    s3BacketName: static.brainjuice.jp